# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shi Li
email: shili@saicmotor.com
description: "I practice my saxophone three hours a day. I’m not saying I’m particularly special, but if you do something three hours a day for forty years, you get pretty good at it. -- Kenny G"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://LinkRogers.github.io/" # the base hostname & protocol for your site
github_username:  LinkRogers

# Build settings
markdown: kramdown
