# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yunjie Yang
email: yunjiey@mit.edu
description: "It doesn't matter how beautiful your theory is, it doesn't matter how smart you are.
If it doesn't agree with experiment, it's wrong. -- Richard P. Feynman"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yunjie-yang.github.io/" # the base hostname & protocol for your site
github_username:  yunjie-yang

# Build settings
markdown: kramdown
